apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: argo-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: apache
