apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-deployment
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tst-argocd
    server: https://kubernets.default.svc
  project: default
  source:
    path: app_deployment_manifests/apache-deployment
    reploURL: https://github.com/jpenn-dcli/kube-manifests
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true