apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-deployment
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    reploURL: https://github.com/dcli-com/cloud-lib/kube-manifests
    path: app_deployment_manifests/apache-deployment
    targetRevision: master
destination:
    namespace: argo-demo
    server: https://kubernets.default.svc
syncPolicy:
  automated:
    selfHeal: true
    syncOptions:
      - CreateNamespace=true